# Generated by Django 4.2.5 on 2023-10-25 21:32

from django.db import migrations, models
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identity_informations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, validators=[myapp.models.validate_uuid])),
                ('first_name', models.CharField(blank=True, max_length=99)),
                ('last_name', models.CharField(blank=True, max_length=99)),
                ('sexe', models.CharField(blank=True, choices=[('MA', 'Men'), ('FE', 'women')], max_length=2)),
                ('date_of_birth', models.DateField(blank=True)),
                ('addresses', models.CharField(blank=True, max_length=99)),
                ('city', models.CharField(blank=True, max_length=99)),
                ('date_depot', models.DateField(blank=True)),
                ('date_expirated', models.DateField(blank=True)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('confidentiality', models.BooleanField(default=False)),
                ('image_recto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_verso', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
